import "../css/letter.css";
const letterPhotos=[[28,"A Memory I Keep Close"],[41,"A Smile To Remember"],[18,"A Beautiful Chapter"],[19,"Always In My Heart"]];
export default function LetterPage(){return <section className="letter-page"><div className="letter-page-bg"/><div className="letter-page-container">
<div className="letter-page-header"><span className="letter-page-tag">💌 A MESSAGE FROM MY HEART</span><h1>A Special Birthday Letter</h1><p>Some people become special slowly, but their place in our heart becomes priceless. ❤️</p></div>
<div className="birthday-letter-card"><div className="letter-top-icon">🎂</div><div className="letter-decoration">❤️ ✨ 🌹 ✨ ❤️</div><h2>Happy Birthday My Dear Falak ❤️</h2>
<div className="letter-image"><img src="/images/6311860629874087186_121.jpg" alt="Falak"/></div>
<div className="letter-photo-gallery">{letterPhotos.map(([n,title],i)=><figure key={n}><img src={`/images/pdf_${String(n).padStart(2,"0")}.jpg`} alt={`Birthday letter memory ${i+1}`}/><figcaption>{title} ❤️</figcaption></figure>)}</div>
<div className="letter-line"/><div className="letter-message"><p><strong>Dear Falak ❤️,</strong></p><p>Today is one of the most beautiful and special days because it is your birthday. On this lovely day, I pray that Allah always keeps you happy, healthy, successful and smiling.</p><p>May every dream of yours come true, may every difficulty become easy, and may your life always be filled with happiness, peace, love and countless blessings. 🤲✨</p><p>Thank you for becoming such an important part of my life. You are my happiness, my peace, my favorite person and one of the biggest blessings in my life.</p><p>Every conversation with you feels special. Your smile makes me happy, your words give me peace, and your presence makes ordinary moments feel beautiful.</p><div className="letter-special-box"><span>💖</span><p>“You are not only a beautiful part of my life, you are the reason many ordinary days become special.” ❤️</p></div><p>I promise to always respect you, care for you and support you. I will always value our relationship and try my best to keep you happy.</p><div className="shayari-box"><h3>🌹 A Few Words For You</h3><p>Teri muskaan meri khushi ban jaati hai,<br/>Teri har baat dil ko chhoo jaati hai,<br/>Door hokar bhi tu dil ke paas rehti hai,<br/>Falak, tu meri zindagi ko khoobsurat bana jaati hai. ❤️</p></div><p>Always keep smiling and always believe in yourself. You deserve every happiness and every beautiful thing in this world.</p><div className="final-birthday-wish">🎂 Happy Birthday My Princess ❤️<span>May your life always shine with happiness and success ✨</span></div></div>
<div className="letter-signature"><p>With lots of love,</p><h3>Shahid Anwar ❤️</h3><span>Forever wishing for your happiness</span></div></div>
<div className="letter-page-footer"><span>🌹 ❤️ ✨</span><h2>You Will Always Be Special To Me</h2><p>Every birthday of yours is a beautiful reason for me to pray for your happiness.</p></div></div></section>}
